### ISSUE TITLE
Posible caída de las respuestas HTTP del servidor.

### ISSUE THREAD

**Issue by PabloCorbCon** [faztcommunity/fazt-oficial-web#58]
Buenos días, intentando acceder a la página web que se proporciona en el perfil de la organización **he recibido un error http "SERVER NOT FOUND"** o "servidor no encontrado".

**Haciendo** `ping` **a la dirección del "servidor"**  no obtengo ninguna respuesta por lo que doy por echo que o han **bloqueado las peticiones no seguras para evitar un ataque pingflood** o **el servidor no puede responder**

#### Como sugerencias: 
Hay muchas razones por las que podría recibir este error, ni siquiera se sí la página está hosteada en un servidor o simplemente han reservado el dominio y aún no han desplegado la página. En tal caso no tienen ningun problema.

En caso de que ya hayan desplegado la página, les recomiendo que comprueben el estado del servidor en su probeedor de servicios. La mayor parte de provedores pueden proporcionar el archivo de Logs del servidor.

Si son ustedes los que mantienen el servidor de la página, es decir mantienen está en un servidor físico comprueben que este está activo y que no han sufrido ningun tipo de ataque DDoS o similar.

#### Ahora algo de información sobre mí, en caso de que les sea útil:
* Sistema operativo:  [Ubuntu 20.04+](https://ubuntu.com/)  / [Kali live 2020.3](https://www.kali.org/)
* Arquitectura del sistema: 64b
* Conectividad: Lan-inh NET
* VPN: [NordVPN](https://nordvpn.com/es/) desde WEST-EEUU
* Navegador: [Mozzila](https://www.mozilla.org/es-ES/firefox/new/) / [Tor](https://www.torproject.org/)
* Puertos bloqueados en el momento de efectuar la conexión: [12-50, 124, 166, 167, 3000-3030, 5550]
![Captura de pantalla de 2020-10-19 14-02-07](https://user-images.githubusercontent.com/63709477/96451186-803d9780-1217-11eb-869c-1aea144b0fb6.png)
###### Un saludo desde Murcia, España

**Comment by leave20** [comment]
Se dió de baja el dominio de la pagina , el mismo Fazt lo hizo por motivos personales

**Comment by PabloCorbCon** [comment]
No tenia idea. Disculpe.
